import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// แก้ไข Path ให้ตรงกับชื่อโฟลเดอร์ Component ของคุณ
import Navigation from "../Components/Navbar"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navigation />
        
        <main className="flex-grow pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}